name: Create Releases

on:
  release:
    types:
      - published

jobs:
  bump-and-npm:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-24.04
        node-version:
          - '20'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          cache: npm
      - name: Install dependencies
        run: npm clean-install --prefer-offline --frozen-lockfile
      - name: Lint code
        run: npm run lint
      - name: Run unit tests
        run: npm run test:unit
      - name: Prepare Release
        uses: lando/prepare-release-action@v3
        with:
          lando-plugin: true
          sync: false
      - name: Publish to npm
        run: |
          VERSION=$(node -p "require('./package.json').version")
          PACKAGE=$(node -p "require('./package.json').name")

          if [ "${{ github.event.release.prerelease }}" ==  "false" ]; then
            npm publish --access public --dry-run
            npm publish --access public
            npm dist-tag add "$PACKAGE@$VERSION" edge

            echo "::notice title=Published $VERSION to $PACKAGE::This is a stable release published to the default 'latest' npm tag"
            echo "::notice title=Updated latest tag to $VERSION::The stable tag now points to $VERSION"
            echo "::notice title=Updated edge tag to $VERSION::The edge tag now points to $VERSION"
          else
            npm publish --access public --tag edge --dry-run
            npm publish --access public --tag edge

            echo "::notice title=Published $VERSION to $PACKAGE::This is a prerelease published to the 'edge' npm tag"
            echo "::notice title=Updated edge tag to $VERSION::The edge tag now points to $VERSION"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
